CREATE TABLE batting_data (
    Batting VARCHAR(255),
    AB NUMERIC,
    R NUMERIC,
    H NUMERIC,
    RBI NUMERIC,
    BB NUMERIC,
    SO NUMERIC,
    PA NUMERIC,
    BA NUMERIC,
    OBP NUMERIC,
    SLG NUMERIC,
    OPS NUMERIC,
    Pit NUMERIC,
    Str NUMERIC,
    WPA NUMERIC,
    aLI NUMERIC,
    WPAplus NUMERIC,
    WPAminus NUMERIC,
    cWPA NUMERIC,
    acLI NUMERIC,
    RE24 NUMERIC,
    PO NUMERIC,
    A NUMERIC,
    Details VARCHAR(255),
    "Batting-additional" VARCHAR(255),
    upload_dttm DATE
);